[project]
requires-python = ">=3.13,<3.14"
name = "bar-price-builder"
version = "0.1.0"
description = ""
readme = "README.md"

[tool.poetry]
authors = ["St Mary's Church, Whitkirk Technology Team <tech@whitkirkchurch.org.uk>"]
package-mode = false

[tool.poetry.dependencies]
python = "==3.13.14"
weasyprint = "69.0"
click = "8.5.0"
jinja2 = "3.1.6"
pytz = "2026.3.post1"
requests = "2.34.2"
"ruamel.yaml" = "0.19.1"
pillow = "12.3.0"

[tool.poetry.group.dev.dependencies]
json-schema-for-humans = "1.5.1"
pytest = "9.1.1"
boto3 = "1.43.85"

[tool.ruff]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
ignore = ["E501", "G004", "PLR2004", "RUF005", "RUF012", "UP040"] # long lines, fstrings in logs, magic values, consider not concat, mutable classbits, type instead of TypeAlias
extend-select = ["W", "B", "Q", "C90", "I", "UP", "YTT", "ASYNC", "S", "BLE", "A", "COM", "C4", "DTZ", "T10", "DJ", "EM", "EXE", "FA",
                 "ISC", "ICN", "G", "INP", "PIE", "T20", "PYI", "PT", "Q", "RSE", "RET", "SLF", "SLOT", "SIM", "TID", "TCH", "INT", "PTH",
                 "FIX", "PGH", "PL", "TRY", "FLY", "PERF", "RUF"]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["S101", "S106", "SLF001", "PLR0913"]

[tool.djlint]
ignore="H030,H031"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
